FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Copy the .env file to the container
COPY .env .env

# Set the environment variable
ENV $(cat .env | xargs)

CMD ["python", "run.py"]
